# Python Project Idea: Naukri Job Market Analysis (March 2023)

In [ ]:
#Import the Necessary Libraries

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter

In [6]:
df = pd.read_csv("Naukri Jobs Data - Mar 2023.csv")
df.head()

,title,company,starRating,reviewsCount,experience,salary,location,job-description,skill_1,skill_2,skill_3,skill_4,skill_5,skill_6,skill_7,skill_8,posted on,Dept
0,Customer Engineer,NCR Corporation,4.0,1026 Reviews,2-7 Yrs,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Provides prompt and courteous service response...,n+,customer engineering,service level,inventory,recruitment,technology,customer satisfaction,a+,1 Day Ago,"Customer Success, service & Operation"
1,Service Operation Manager,Rackspace Technology,4.0,20 Reviews,4-8 Yrs,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Managing a busy change team mailbox and ticket...,incident management,technology management,rackspace,rca,change management,service operations,ticketing,analysis,1 Day Ago,"Customer Success, service & Operation"
2,Service Operation Manager,Rackspace Technology,4.0,20 Reviews,4-9 Yrs,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Managing a busy change team mailbox and ticket...,technology management,rackspace,delivery,change management,service operations,ticketing,analysis,operations management,1 Day Ago,"Customer Success, service & Operation"
3,"Senior Manager, Business Operations",Rackspace Technology,4.0,20 Reviews,3-15 Yrs,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Required bachelor s degree in data analytics o...,business operations,automation,senior management,intelligence,project,mis,analysis,management,1 Day Ago,"Customer Success, service & Operation"
4,Technical Support/ Customer Service Representa...,TELUS International,4.1,238 Reviews,0-3 Yrs,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad/Secunder...",Provides top quality customer service / techni...,csr,customer service,inbound,technical,sales,process,sales process,customer interaction,5 Days Ago,"Customer Success, service & Operation"

In [7]:
df.tail()

,title,company,starRating,reviewsCount,experience,salary,location,job-description,skill_1,skill_2,skill_3,skill_4,skill_5,skill_6,skill_7,skill_8,posted on,Dept
94506,Urgent Hiring For Graphic Designers,Romsons Group,4.0,213 Reviews,2-5 Yrs,Not disclosed,"Noida, Ghaziabad, Delhi / NCR",Good technical skills and proven ability to us...,Coral,Photoshop,Graphic Designing,HTML Coding,design,coding,graphics,html,23 Days Ago,"UX, Design & Architecture"
94507,Graphic Designer,Advarohi,NaN,NaN,1-5 Yrs,2.5-3 Lacs PA,Agra,RESPONSIBILITIES 1. Communicating with clients...,Graphic Designing,communication skills,punctual,computer literate,computer,adobe,design,graphics,24 Days Ago,"UX, Design & Architecture"
94508,Web Developer (Immediate Joiner),Pandaje Web Services,3.6,16 Reviews,4-5 Yrs,8-10 Lacs PA,"Noida, Ghaziabad, Delhi / NCR","Website and software application designing, bu...",Web Development,php wordpress,php,wordpress,web technologies,development,NaN,NaN,26 Days Ago,"UX, Design & Architecture"
94509,Graphic Designer - Thane(W),Pulse Pharmaceuticals,3.9,156 Reviews,2-4 Yrs,3-5 Lacs PA,Thane,"Good at CorelDraw, Adobe Illustrator, Photosho...",Corel Draw,graphics,photoshop,flyers,draw,banners,post,corel,28 Days Ago,"UX, Design & Architecture"
94510,Senior Architect and junior architects,LTR architects,NaN,NaN,1-3 Yrs,2.25-3.5 Lacs PA,Hyderabad/Secunderabad,Require 3D visiualizers and 2D draft-man,AutoCAD 2D,VRAY,3Ds Max,rendering,3d,architecture,senior,sketchup,21 Days Ago,"UX, Design & Architecture"

In [8]:
Clean the Data

Handle missing values

Clean salary text (convert to numeric LPA)

Clean experience column

Standardize job titlesb

SyntaxError: invalid syntax (1232490986.py, line 1)

In [ ]:
df.columns

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.isnull().sum()

In [ ]:
# Replace missing company with a placeholder
df['company'] = df['company'].fillna('Unknown Company')

# Salary cleaning
df['salary'] = pd.to_numeric(df['salary'], errors='coerce')
df['salary'] = df['salary'].fillna(0)

# Job description
df['job-description'] = df['job-description'].fillna('No description provided')

# Fill missing skills
skill_cols = ['skill_1','skill_2','skill_3','skill_4',
              'skill_5','skill_6','skill_7','skill_8']

for col in skill_cols:
    df[col] = df[col].fillna("None")

# Posted date
df['posted on'] = df['posted on'].fillna('Unknown')

In [ ]:
df.isnull().sum()

In [ ]:
df['starRating'] = df['starRating'].fillna(0)
df['reviewsCount'] = df['reviewsCount'].fillna(0)

In [ ]:
df.isnull().sum()

In [ ]:
top_roles = df['title'].value_counts().head(10)
plt.figure(figsize=(20,3))  # Set figure size
top_roles.plot(kind='bar')
plt.title("Top 10 Job Roles")
plt.xlabel("Job Title")
plt.ylabel("Count")
plt.show()

# Top Hiring Locations

In [ ]:
plt.figure(figsize=(20,3))

df['location'].value_counts().head(10).plot(kind='bar')

plt.title("Top Hiring Cities")
plt.xlabel("City")
plt.ylabel("Job Count")
plt.show()

# Salary Analysis

In [ ]:
df.groupby("title")["salary"].mean().sort_values(ascending=False).head(10)

In [ ]:
plt.figure(figsize=(20,3))

df.groupby("title")["salary"].mean().sort_values(ascending=False).head(10).plot(kind='bar')

plt.title("Top 10 Highest Paying Job Roles")
plt.xlabel("Job Title")
plt.ylabel("Average Salary (LPA)")
plt.show()

# Experience Requirement Analysis

In [ ]:
df['experience'].value_counts().sort_index().plot(kind='bar')
plt.figure(figsize=(10,5))
plt.title("Experience Required")
plt.xlabel("Years of Experience")
plt.ylabel("Count")
plt.show()

# Find most common skills:

In [ ]:
df.columns

In [ ]:
skill_columns = ['skill_1', 'skill_2', 'skill_3', 'skill_4',
                 'skill_5', 'skill_6', 'skill_7', 'skill_8']

# Flatten all skill columns into one list
all_skills = []

for col in skill_columns:
    all_skills.extend(df[col].dropna().astype(str).str.strip())

# Now get top 20 skills

In [ ]:
from collections import Counter

skill_counts = Counter(all_skills).most_common(20)
skill_counts

In [ ]:
top_skills = dict(skill_counts)

plt.figure(figsize=(20,6))
plt.bar(top_skills.keys(), top_skills.values())
plt.xticks(rotation=45)
plt.title("Top 20 Most Required Skills")
plt.xlabel("Skills")
plt.ylabel("Count")
plt.show()

# Top Hiring Companies

In [ ]:
df['company'].value_counts().head(20)

In [ ]:
df['company'].value_counts().head(5).plot(kind='bar')
plt.title("Top 5 Hiring Companies")
plt.show()

# ime-based Trend (Jobs per Day or per Week)

In [ ]:
df.columns

In [9]:
df['posted on'].head(10)

0      1 Day Ago
1      1 Day Ago
2      1 Day Ago
3      1 Day Ago
4     5 Days Ago
5     5 Days Ago
6     6 Days Ago
7     6 Days Ago
8    13 Days Ago
9     9 Days Ago
Name: posted on, dtype: object

In [11]:
df.to_csv("clean_naukri_jobs.csv", index=False)
print("File saved successfully!")

File saved successfully!